import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogClose,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useData } from '@/context/DataContext';
import { createConceptTemplate } from '@/data/models'; // We'll use this if creating a new one

const TemplateFormModal = ({ open, onOpenChange, templateToEdit, onSave }) => {
  const { t } = useTranslation();
  const [name, setName] = useState('');
  // templateData fields
  const [templateNameField, setTemplateNameField] = useState(''); // Name field within templateData
  const [aliases, setAliases] = useState(''); // Comma-separated
  const [tags, setTags] = useState(''); // Comma-separated
  const [description, setDescription] = useState('');
  const [notes, setNotes] = useState('');
  const [priority, setPriority] = useState(0);
  const [image, setImage] = useState(''); // Base64 string or URL

  useEffect(() => {
    if (templateToEdit) {
      setName(templateToEdit.name || '');
      setTemplateNameField(templateToEdit.templateData?.name || '');
      setAliases((templateToEdit.templateData?.aliases || []).join(', '));
      setTags((templateToEdit.templateData?.tags || []).join(', '));
      setDescription(templateToEdit.templateData?.description || '');
      setNotes(templateToEdit.templateData?.notes || '');
      setPriority(templateToEdit.templateData?.priority || 0);
      setImage(templateToEdit.templateData?.image || '');
    } else {
      // Reset for new template
      setName('');
      setTemplateNameField('');
      setAliases('');
      setTags('');
      setDescription('');
      setNotes('');
      setPriority(0);
      setImage('');
    }
  }, [templateToEdit, open]); //Rerun if modal is opened or templateToEdit changes

  const handleSubmit = () => {
    const templatePayload = {
      id: templateToEdit?.id, // Keep ID if editing, else it will be generated by createConceptTemplate or onSave
      name: name.trim(),
      templateData: {
        name: templateNameField.trim() || undefined, // Store as undefined if empty, so it doesn't override concept name
        aliases: aliases.split(',').map(s => s.trim()).filter(s => s),
        tags: tags.split(',').map(s => s.trim()).filter(s => s),
        description: description.trim(),
        notes: notes.trim(),
        priority: parseInt(priority, 10) || 0,
        image: image.trim() || null,
      },
      // isDefault and creation_date will be handled by onSave or are inherent to templateToEdit
      last_modified_date: Date.now(),
    };
    onSave(templatePayload);
    onOpenChange(false); // Close modal after save
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[525px]">
        <DialogHeader>
          <DialogTitle>{templateToEdit ? t('template_form_modal_title_edit') : t('template_form_modal_title_create')}</DialogTitle>
          <DialogDescription>
            {templateToEdit ? t('template_form_modal_description_edit') : t('template_form_modal_description_create')}
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4 max-h-[70vh] overflow-y-auto pr-2">
          <div className="grid grid-cols-4 items-center gap-4">
            <Label htmlFor="template-display-name" className="text-right">{t('template_form_modal_label_template_name_required')}</Label>
            <Input id="template-display-name" value={name} onChange={(e) => setName(e.target.value)} className="col-span-3" placeholder={t('template_form_modal_placeholder_template_name')} />
          </div>
          
          <p className="text-sm text-muted-foreground col-span-full pt-2 pb-1">{t('template_form_modal_text_prefilled_fields')}</p>

          <div className="grid grid-cols-[max-content_1fr] items-center gap-x-3 gap-y-2">
            <Label htmlFor="template-concept-name" className="text-right whitespace-nowrap">{t('template_form_modal_label_concept_name')}</Label>
            <Input id="template-concept-name" value={templateNameField} onChange={(e) => setTemplateNameField(e.target.value)} placeholder={t('template_form_modal_placeholder_concept_name')} />
          </div>
          <div className="grid grid-cols-[max-content_1fr] items-center gap-x-3 gap-y-2">
            <Label htmlFor="template-aliases" className="text-right whitespace-nowrap">{t('template_form_modal_label_aliases')}</Label>
            <Input id="template-aliases" value={aliases} onChange={(e) => setAliases(e.target.value)} placeholder={t('template_form_modal_placeholder_aliases')} />
          </div>
          <div className="grid grid-cols-[max-content_1fr] items-center gap-x-3 gap-y-2">
            <Label htmlFor="template-tags" className="text-right whitespace-nowrap">{t('template_form_modal_label_tags')}</Label>
            <Input id="template-tags" value={tags} onChange={(e) => setTags(e.target.value)} placeholder={t('template_form_modal_placeholder_tags')} />
          </div>
          <div className="grid grid-cols-[max-content_1fr] items-center gap-x-3 gap-y-2">
            <Label htmlFor="template-priority" className="text-right whitespace-nowrap">{t('template_form_modal_label_priority')}</Label>
            <Input id="template-priority" type="number" value={priority} onChange={(e) => setPriority(e.target.value)} />
          </div>
          
          {/* Description and Notes remain full width */}
          <div className="grid grid-cols-1 gap-y-1 mt-2">
            <Label htmlFor="template-description">{t('template_form_modal_label_description_prefilled')}</Label>
            <Textarea id="template-description" value={description} onChange={(e) => setDescription(e.target.value)} placeholder={t('template_form_modal_placeholder_description')} rows={3}/>
          </div>
          <div className="grid grid-cols-1 gap-y-1 mt-2">
            <Label htmlFor="template-notes">{t('template_form_modal_label_notes_prefilled')}</Label>
            <Textarea id="template-notes" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder={t('template_form_modal_placeholder_notes')} rows={2}/>
          </div>

          <div className="grid grid-cols-[max-content_1fr] items-center gap-x-3 gap-y-2 mt-2">
            <Label htmlFor="template-image" className="text-right whitespace-nowrap">{t('template_form_modal_label_image_url')}</Label>
            <Input id="template-image" value={image} onChange={(e) => setImage(e.target.value)} placeholder={t('template_form_modal_placeholder_image_url')} />
          </div>
        </div>
        <DialogFooter>
          <DialogClose asChild>
            <Button type="button" variant="outline">{t('cancel')}</Button>
          </DialogClose>
          <Button type="submit" onClick={handleSubmit} disabled={!name.trim()}>{t('template_form_modal_button_save_template')}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default TemplateFormModal;
